import type { Database } from "@/lib/models";

const now = "2026-05-15T00:00:00.000Z";

export const seedDatabase: Database = {
  instruments: [
    {
      id: "inst-violin",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Violin",
      instrumentCategory: "Strings",
      isActive: true,
    },
    {
      id: "inst-piano",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Piano",
      instrumentCategory: "Piano",
      isActive: true,
    },
    {
      id: "inst-vocal",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Vocal",
      instrumentCategory: "Vocal",
      isActive: true,
    },
  ],
  rooms: [
    {
      id: "room-strings-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Strings Room 1",
      capacity: 2,
      instrumentIds: ["inst-violin"],
      isActive: true,
    },
    {
      id: "room-piano-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Piano Room 1",
      capacity: 2,
      instrumentIds: ["inst-piano"],
      isActive: true,
    },
    {
      id: "room-vocal-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Vocal Room 1",
      capacity: 2,
      instrumentIds: ["inst-vocal"],
      isActive: true,
    },
  ],
  instructors: [
    {
      id: "instructor-sari",
      createdAt: now,
      updatedAt: now,
      instructorName: "Sari Wijaya",
      instrumentIds: ["inst-violin"],
      levelFrom: "Beginner",
      levelTo: "Advanced",
      portalEnabled: true,
    },
    {
      id: "instructor-budi",
      createdAt: now,
      updatedAt: now,
      instructorName: "Budi Santoso",
      instrumentIds: ["inst-piano"],
      levelFrom: "Beginner",
      levelTo: "Advanced",
      portalEnabled: true,
    },
    {
      id: "instructor-maya",
      createdAt: now,
      updatedAt: now,
      instructorName: "Maya Putri",
      instrumentIds: ["inst-vocal"],
      levelFrom: "Beginner",
      levelTo: "Intermediate",
      portalEnabled: true,
    },
  ],
  guardians: [
    {
      id: "guardian-dewi",
      createdAt: now,
      updatedAt: now,
      guardianName: "Dewi Hartono",
      mobileNumber: "081234567891",
    },
    {
      id: "guardian-rina",
      createdAt: now,
      updatedAt: now,
      guardianName: "Rina Prameswari",
      mobileNumber: "081234567892",
    },
    {
      id: "guardian-andi",
      createdAt: now,
      updatedAt: now,
      guardianName: "Andi Saputra",
      mobileNumber: "081234567893",
    },
  ],
  students: [
    {
      id: "student-luna",
      createdAt: now,
      updatedAt: now,
      firstName: "Luna",
      lastName: "Hartono",
      skillLevel: "Beginner",
      learningGoal: "Performance",
      guardianIds: ["guardian-dewi"],
      portalEnabled: true,
      musicNotes: "Mulai dari postur bowing dasar.",
    },
    {
      id: "student-ayu",
      createdAt: now,
      updatedAt: now,
      firstName: "Ayu",
      lastName: "Prameswari",
      skillLevel: "Beginner",
      learningGoal: "Technique",
      guardianIds: ["guardian-rina"],
      portalEnabled: true,
      musicNotes: "Fokus koordinasi tangan kanan dan kiri.",
    },
    {
      id: "student-nara",
      createdAt: now,
      updatedAt: now,
      firstName: "Nara",
      lastName: "Saputra",
      skillLevel: "Intermediate",
      learningGoal: "Confidence",
      guardianIds: ["guardian-andi"],
      portalEnabled: true,
      musicNotes: "Latihan pernapasan dan artikulasi.",
    },
  ],
  courses: [
    {
      id: "course-violin-beginner",
      createdAt: now,
      updatedAt: now,
      courseName: "Violin Beginner Private",
      instrumentId: "inst-violin",
      courseLevel: "Beginner",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 900000,
    },
    {
      id: "course-piano-beginner",
      createdAt: now,
      updatedAt: now,
      courseName: "Piano Beginner Private",
      instrumentId: "inst-piano",
      courseLevel: "Beginner",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 850000,
    },
    {
      id: "course-vocal-intermediate",
      createdAt: now,
      updatedAt: now,
      courseName: "Vocal Intermediate Private",
      instrumentId: "inst-vocal",
      courseLevel: "Intermediate",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 800000,
    },
  ],
  "lesson-packages": [
    {
      id: "package-luna-2026-05",
      createdAt: now,
      updatedAt: now,
      studentId: "student-luna",
      courseId: "course-violin-beginner",
      instructorId: "instructor-sari",
      instrumentId: "inst-violin",
      billingPeriod: "2026-05",
      lessonStartDate: "2026-05-15",
      lessonDays: ["6"],
      lessonCount: 4,
      fromTime: "09:00",
      toTime: "10:00",
      lessonMode: "Studio",
      studioRoomId: "room-strings-1",
      homeVisitAddress: "",
      status: "Active",
    },
    {
      id: "package-ayu-2026-05",
      createdAt: now,
      updatedAt: now,
      studentId: "student-ayu",
      courseId: "course-piano-beginner",
      instructorId: "instructor-budi",
      instrumentId: "inst-piano",
      billingPeriod: "2026-05",
      lessonStartDate: "2026-05-01",
      lessonDays: ["1"],
      lessonCount: 4,
      fromTime: "15:00",
      toTime: "16:00",
      lessonMode: "Studio",
      studioRoomId: "room-piano-1",
      homeVisitAddress: "",
      status: "Active",
    },
    {
      id: "package-ayu-2026-06",
      createdAt: now,
      updatedAt: now,
      studentId: "student-ayu",
      courseId: "course-piano-beginner",
      instructorId: "instructor-budi",
      instrumentId: "inst-piano",
      billingPeriod: "2026-06",
      lessonStartDate: "2026-06-01",
      lessonDays: ["1"],
      lessonCount: 4,
      fromTime: "15:00",
      toTime: "16:00",
      lessonMode: "Studio",
      studioRoomId: "room-piano-1",
      homeVisitAddress: "",
      status: "Active",
    },
    {
      id: "package-nara-2026-05",
      createdAt: now,
      updatedAt: now,
      studentId: "student-nara",
      courseId: "course-vocal-intermediate",
      instructorId: "instructor-maya",
      instrumentId: "inst-vocal",
      billingPeriod: "2026-05",
      lessonStartDate: "2026-05-15",
      lessonDays: ["3"],
      lessonCount: 4,
      fromTime: "19:00",
      toTime: "20:00",
      lessonMode: "Home Visit",
      studioRoomId: "",
      homeVisitAddress: "Jl. Melodi No. 22, Jakarta Selatan",
      status: "Active",
    },
  ],
  schedules: [],
  "student-attendance": [],
  "instructor-attendance": [],
  journals: [],
  repertoires: [
    {
      id: "rep-twinkle-violin",
      createdAt: now,
      updatedAt: now,
      title: "Twinkle Twinkle Little Star",
      composerArtist: "Traditional",
      instrumentId: "inst-violin",
      level: "Beginner",
      genre: "Traditional",
      notes: "Latihan intonasi dan bowing dasar.",
      isActive: true,
    },
    {
      id: "rep-minuet-g",
      createdAt: now,
      updatedAt: now,
      title: "Minuet in G",
      composerArtist: "J. S. Bach",
      instrumentId: "inst-piano",
      level: "Beginner",
      genre: "Classical",
      notes: "Latihan koordinasi dua tangan.",
      isActive: true,
    },
    {
      id: "rep-stand-by-me",
      createdAt: now,
      updatedAt: now,
      title: "Stand by Me",
      composerArtist: "Ben E. King",
      instrumentId: "inst-vocal",
      level: "Intermediate",
      genre: "Pop",
      notes: "Latihan phrasing dan kontrol napas.",
      isActive: true,
    },
  ],
  invoices: [],
  notifications: [],
};

export const seedUsers = [
  {
    email: "admin@akres.test",
    name: "Administrator Akres",
    role: "System Manager",
    studentId: "",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "luna.student@akres.test",
    name: "Luna Hartono",
    role: "Student Portal User",
    studentId: "student-luna",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "ayu.student@akres.test",
    name: "Ayu Prameswari",
    role: "Student Portal User",
    studentId: "student-ayu",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "nara.student@akres.test",
    name: "Nara Saputra",
    role: "Student Portal User",
    studentId: "student-nara",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "dewi.parent@akres.test",
    name: "Dewi Hartono",
    role: "Parent Portal User",
    studentId: "",
    guardianId: "guardian-dewi",
    instructorId: "",
  },
  {
    email: "rina.parent@akres.test",
    name: "Rina Prameswari",
    role: "Parent Portal User",
    studentId: "",
    guardianId: "guardian-rina",
    instructorId: "",
  },
  {
    email: "andi.parent@akres.test",
    name: "Andi Saputra",
    role: "Parent Portal User",
    studentId: "",
    guardianId: "guardian-andi",
    instructorId: "",
  },
  {
    email: "sari.teacher@akres.test",
    name: "Sari Wijaya",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-sari",
  },
  {
    email: "budi.teacher@akres.test",
    name: "Budi Santoso",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-budi",
  },
  {
    email: "maya.teacher@akres.test",
    name: "Maya Putri",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-maya",
  },
];
