import type { Database } from "@/lib/models";

const now = "2026-05-15T00:00:00.000Z";

export const seedDatabase: Database = {
  instruments: [
    {
      id: "inst-violin",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Violin",
      instrumentCategory: "Strings",
      isActive: true,
    },
    {
      id: "inst-piano",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Piano",
      instrumentCategory: "Piano",
      isActive: true,
    },
    {
      id: "inst-vocal",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Vocal",
      instrumentCategory: "Vocal",
      isActive: true,
    },
    {
      id: "inst-guitar",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Guitar",
      instrumentCategory: "Guitar",
      isActive: true,
    },
    {
      id: "inst-drums",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Drums",
      instrumentCategory: "Drums",
      isActive: true,
    },
  ],
  rooms: [
    {
      id: "room-strings-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Strings Room 1",
      capacity: 2,
      instrumentIds: ["inst-violin"],
      isActive: true,
    },
    {
      id: "room-piano-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Piano Room 1",
      capacity: 2,
      instrumentIds: ["inst-piano"],
      isActive: true,
    },
    {
      id: "room-vocal-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Vocal Room 1",
      capacity: 2,
      instrumentIds: ["inst-vocal"],
      isActive: true,
    },
    {
      id: "room-guitar-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Guitar Room 1",
      capacity: 2,
      instrumentIds: ["inst-guitar"],
      isActive: true,
    },
    {
      id: "room-drums-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Drums Room 1",
      capacity: 2,
      instrumentIds: ["inst-drums"],
      isActive: true,
    },
  ],
  instructors: [
    {
      id: "instructor-sari",
      createdAt: now,
      updatedAt: now,
      instructorName: "Sari Wijaya",
      instrumentIds: ["inst-violin"],
      levelFrom: "Beginner",
      levelTo: "Advanced",
      portalEnabled: true,
    },
    {
      id: "instructor-budi",
      createdAt: now,
      updatedAt: now,
      instructorName: "Budi Santoso",
      instrumentIds: ["inst-piano"],
      levelFrom: "Beginner",
      levelTo: "Advanced",
      portalEnabled: true,
    },
    {
      id: "instructor-maya",
      createdAt: now,
      updatedAt: now,
      instructorName: "Maya Putri",
      instrumentIds: ["inst-vocal"],
      levelFrom: "Beginner",
      levelTo: "Intermediate",
      portalEnabled: true,
    },
    {
      id: "instructor-jason",
      createdAt: now,
      updatedAt: now,
      instructorName: "Jason Tan",
      instrumentIds: ["inst-guitar"],
      levelFrom: "Beginner",
      levelTo: "Advanced",
      portalEnabled: true,
    },
    {
      id: "instructor-raka",
      createdAt: now,
      updatedAt: now,
      instructorName: "Raka Mahendra",
      instrumentIds: ["inst-drums"],
      levelFrom: "Beginner",
      levelTo: "Advanced",
      portalEnabled: true,
    },
  ],
  guardians: [
    {
      id: "guardian-dewi",
      createdAt: now,
      updatedAt: now,
      guardianName: "Dewi Hartono",
      mobileNumber: "081234567891",
    },
    {
      id: "guardian-rina",
      createdAt: now,
      updatedAt: now,
      guardianName: "Rina Prameswari",
      mobileNumber: "081234567892",
    },
    {
      id: "guardian-andi",
      createdAt: now,
      updatedAt: now,
      guardianName: "Andi Saputra",
      mobileNumber: "081234567893",
    },
  ],
  students: [
    {
      id: "student-luna",
      createdAt: now,
      updatedAt: now,
      firstName: "Luna",
      lastName: "Hartono",
      skillLevel: "Beginner",
      learningGoal: "Performance",
      guardianIds: ["guardian-dewi"],
      portalEnabled: true,
      musicNotes: "Mulai dari postur bowing dasar.",
    },
    {
      id: "student-ayu",
      createdAt: now,
      updatedAt: now,
      firstName: "Ayu",
      lastName: "Prameswari",
      skillLevel: "Beginner",
      learningGoal: "Technique",
      guardianIds: ["guardian-rina"],
      portalEnabled: true,
      musicNotes: "Fokus koordinasi tangan kanan dan kiri.",
    },
    {
      id: "student-nara",
      createdAt: now,
      updatedAt: now,
      firstName: "Nara",
      lastName: "Saputra",
      skillLevel: "Intermediate",
      learningGoal: "Confidence",
      guardianIds: ["guardian-andi"],
      portalEnabled: true,
      musicNotes: "Latihan pernapasan dan artikulasi.",
    },
  ],
  courses: [
    {
      id: "course-violin-beginner",
      createdAt: now,
      updatedAt: now,
      courseName: "Violin Beginner Private",
      instrumentId: "inst-violin",
      courseLevel: "Beginner",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 900000,
    },
    {
      id: "course-piano-beginner",
      createdAt: now,
      updatedAt: now,
      courseName: "Piano Beginner Private",
      instrumentId: "inst-piano",
      courseLevel: "Beginner",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 850000,
    },
    {
      id: "course-vocal-intermediate",
      createdAt: now,
      updatedAt: now,
      courseName: "Vocal Intermediate Private",
      instrumentId: "inst-vocal",
      courseLevel: "Intermediate",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 800000,
    },
    {
      id: "course-guitar-beginner",
      createdAt: now,
      updatedAt: now,
      courseName: "Guitar Beginner Private",
      instrumentId: "inst-guitar",
      courseLevel: "Beginner",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 800000,
    },
    {
      id: "course-drums-beginner",
      createdAt: now,
      updatedAt: now,
      courseName: "Drums Beginner Private",
      instrumentId: "inst-drums",
      courseLevel: "Beginner",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 850000,
    },
  ],
  "lesson-packages": [
    {
      id: "package-luna-2026-05",
      createdAt: now,
      updatedAt: now,
      studentId: "student-luna",
      courseId: "course-violin-beginner",
      instructorId: "instructor-sari",
      instrumentId: "inst-violin",
      billingPeriod: "2026-05",
      lessonStartDate: "2026-05-15",
      lessonDays: ["6"],
      lessonCount: 4,
      fromTime: "09:00",
      toTime: "10:00",
      lessonMode: "Studio",
      studioRoomId: "room-strings-1",
      homeVisitAddress: "",
      status: "Active",
    },
    {
      id: "package-ayu-2026-05",
      createdAt: now,
      updatedAt: now,
      studentId: "student-ayu",
      courseId: "course-piano-beginner",
      instructorId: "instructor-budi",
      instrumentId: "inst-piano",
      billingPeriod: "2026-05",
      lessonStartDate: "2026-05-01",
      lessonDays: ["1"],
      lessonCount: 4,
      fromTime: "15:00",
      toTime: "16:00",
      lessonMode: "Studio",
      studioRoomId: "room-piano-1",
      homeVisitAddress: "",
      status: "Active",
    },
    {
      id: "package-ayu-2026-06",
      createdAt: now,
      updatedAt: now,
      studentId: "student-ayu",
      courseId: "course-piano-beginner",
      instructorId: "instructor-budi",
      instrumentId: "inst-piano",
      billingPeriod: "2026-06",
      lessonStartDate: "2026-06-01",
      lessonDays: ["1"],
      lessonCount: 4,
      fromTime: "15:00",
      toTime: "16:00",
      lessonMode: "Studio",
      studioRoomId: "room-piano-1",
      homeVisitAddress: "",
      status: "Active",
    },
    {
      id: "package-nara-2026-05",
      createdAt: now,
      updatedAt: now,
      studentId: "student-nara",
      courseId: "course-vocal-intermediate",
      instructorId: "instructor-maya",
      instrumentId: "inst-vocal",
      billingPeriod: "2026-05",
      lessonStartDate: "2026-05-15",
      lessonDays: ["3"],
      lessonCount: 4,
      fromTime: "19:00",
      toTime: "20:00",
      lessonMode: "Home Visit",
      studioRoomId: "",
      homeVisitAddress: "Jl. Melodi No. 22, Jakarta Selatan",
      status: "Active",
    },
  ],
  schedules: [],
  "student-attendance": [],
  "instructor-attendance": [],
  journals: [],
  repertoires: [
    {
      id: "rep-twinkle-violin",
      createdAt: now,
      updatedAt: now,
      title: "Twinkle Twinkle Little Star",
      composerArtist: "Traditional",
      instrumentId: "inst-violin",
      level: "Beginner",
      genre: "Traditional",
      notes: "Latihan intonasi dan bowing dasar.",
      isActive: true,
    },
    {
      id: "rep-ode-to-joy-violin",
      createdAt: now,
      updatedAt: now,
      title: "Ode to Joy",
      composerArtist: "L. v. Beethoven",
      instrumentId: "inst-violin",
      level: "Beginner",
      genre: "Classical",
      notes: "Latihan fingering sederhana dan phrasing.",
      isActive: true,
    },
    {
      id: "rep-gavotte-violin",
      createdAt: now,
      updatedAt: now,
      title: "Gavotte",
      composerArtist: "F. J. Gossec",
      instrumentId: "inst-violin",
      level: "Intermediate",
      genre: "Classical",
      notes: "Latihan artikulasi, bow control, dan dinamika.",
      isActive: true,
    },
    {
      id: "rep-minuet-g",
      createdAt: now,
      updatedAt: now,
      title: "Minuet in G",
      composerArtist: "J. S. Bach",
      instrumentId: "inst-piano",
      level: "Beginner",
      genre: "Classical",
      notes: "Latihan koordinasi dua tangan.",
      isActive: true,
    },
    {
      id: "rep-fur-elise",
      createdAt: now,
      updatedAt: now,
      title: "Fur Elise",
      composerArtist: "L. v. Beethoven",
      instrumentId: "inst-piano",
      level: "Intermediate",
      genre: "Classical",
      notes: "Latihan arpeggio, voicing, dan kontrol tempo.",
      isActive: true,
    },
    {
      id: "rep-c-major-scale-piano",
      createdAt: now,
      updatedAt: now,
      title: "C Major Scale",
      composerArtist: "Technique",
      instrumentId: "inst-piano",
      level: "Beginner",
      genre: "Technique",
      notes: "Latihan fingering dasar dan sinkronisasi tangan.",
      isActive: true,
    },
    {
      id: "rep-stand-by-me",
      createdAt: now,
      updatedAt: now,
      title: "Stand by Me",
      composerArtist: "Ben E. King",
      instrumentId: "inst-vocal",
      level: "Intermediate",
      genre: "Pop",
      notes: "Latihan phrasing dan kontrol napas.",
      isActive: true,
    },
    {
      id: "rep-count-on-me-vocal",
      createdAt: now,
      updatedAt: now,
      title: "Count on Me",
      composerArtist: "Bruno Mars",
      instrumentId: "inst-vocal",
      level: "Beginner",
      genre: "Pop",
      notes: "Latihan pitch accuracy dan artikulasi pop.",
      isActive: true,
    },
    {
      id: "rep-vocal-breathing-warmup",
      createdAt: now,
      updatedAt: now,
      title: "Breathing Warmup",
      composerArtist: "Technique",
      instrumentId: "inst-vocal",
      level: "Beginner",
      genre: "Technique",
      notes: "Latihan napas diafragma dan humming.",
      isActive: true,
    },
    {
      id: "rep-wonderwall-guitar",
      createdAt: now,
      updatedAt: now,
      title: "Wonderwall",
      composerArtist: "Oasis",
      instrumentId: "inst-guitar",
      level: "Beginner",
      genre: "Pop Rock",
      notes: "Latihan strumming pattern dan perpindahan chord.",
      isActive: true,
    },
    {
      id: "rep-hotel-california-guitar",
      createdAt: now,
      updatedAt: now,
      title: "Hotel California",
      composerArtist: "Eagles",
      instrumentId: "inst-guitar",
      level: "Intermediate",
      genre: "Rock",
      notes: "Latihan picking, chord progression, dan phrasing.",
      isActive: true,
    },
    {
      id: "rep-guitar-open-chords",
      createdAt: now,
      updatedAt: now,
      title: "Open Chords Exercise",
      composerArtist: "Technique",
      instrumentId: "inst-guitar",
      level: "Beginner",
      genre: "Technique",
      notes: "Latihan G, C, D, Em dan transisi chord.",
      isActive: true,
    },
    {
      id: "rep-drums-basic-rock",
      createdAt: now,
      updatedAt: now,
      title: "Basic Rock Groove",
      composerArtist: "Technique",
      instrumentId: "inst-drums",
      level: "Beginner",
      genre: "Technique",
      notes: "Latihan koordinasi kick, snare, dan hi-hat.",
      isActive: true,
    },
    {
      id: "rep-drums-8th-note-fill",
      createdAt: now,
      updatedAt: now,
      title: "8th Note Drum Fill",
      composerArtist: "Technique",
      instrumentId: "inst-drums",
      level: "Beginner",
      genre: "Technique",
      notes: "Latihan fill sederhana antar tom dan snare.",
      isActive: true,
    },
    {
      id: "rep-back-in-black-drums",
      createdAt: now,
      updatedAt: now,
      title: "Back in Black",
      composerArtist: "AC/DC",
      instrumentId: "inst-drums",
      level: "Intermediate",
      genre: "Rock",
      notes: "Latihan groove rock stabil dan aksen.",
      isActive: true,
    },
  ],
  invoices: [],
  notifications: [],
};

export const seedUsers = [
  {
    email: "admin@akres.test",
    name: "Administrator Akres",
    role: "System Manager",
    studentId: "",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "luna.student@akres.test",
    name: "Luna Hartono",
    role: "Student Portal User",
    studentId: "student-luna",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "ayu.student@akres.test",
    name: "Ayu Prameswari",
    role: "Student Portal User",
    studentId: "student-ayu",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "nara.student@akres.test",
    name: "Nara Saputra",
    role: "Student Portal User",
    studentId: "student-nara",
    guardianId: "",
    instructorId: "",
  },
  {
    email: "dewi.parent@akres.test",
    name: "Dewi Hartono",
    role: "Parent Portal User",
    studentId: "",
    guardianId: "guardian-dewi",
    instructorId: "",
  },
  {
    email: "rina.parent@akres.test",
    name: "Rina Prameswari",
    role: "Parent Portal User",
    studentId: "",
    guardianId: "guardian-rina",
    instructorId: "",
  },
  {
    email: "andi.parent@akres.test",
    name: "Andi Saputra",
    role: "Parent Portal User",
    studentId: "",
    guardianId: "guardian-andi",
    instructorId: "",
  },
  {
    email: "sari.teacher@akres.test",
    name: "Sari Wijaya",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-sari",
  },
  {
    email: "budi.teacher@akres.test",
    name: "Budi Santoso",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-budi",
  },
  {
    email: "maya.teacher@akres.test",
    name: "Maya Putri",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-maya",
  },
  {
    email: "jason.teacher@akres.test",
    name: "Jason Tan",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-jason",
  },
  {
    email: "raka.teacher@akres.test",
    name: "Raka Mahendra",
    role: "Music Instructor",
    studentId: "",
    guardianId: "",
    instructorId: "instructor-raka",
  },
];
