import type { Database } from "@/lib/models";

const now = "2026-05-10T10:00:00.000Z";

export const seedDatabase: Database = {
  instruments: [
    {
      id: "inst-piano",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Piano",
      instrumentCategory: "Piano",
      isActive: true,
    },
    {
      id: "inst-vocal",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Vocal",
      instrumentCategory: "Vocal",
      isActive: true,
    },
    {
      id: "inst-guitar",
      createdAt: now,
      updatedAt: now,
      instrumentName: "Guitar",
      instrumentCategory: "Guitar",
      isActive: true,
    },
  ],
  guardians: [
    {
      id: "guardian-rina",
      createdAt: now,
      updatedAt: now,
      guardianName: "Rina Prameswari",
      emailAddress: "rina.parent@akres.test",
      mobileNumber: "081234567890",
      user: "rina.parent@akres.test",
    },
  ],
  students: [
    {
      id: "student-ayu",
      createdAt: now,
      updatedAt: now,
      firstName: "Ayu",
      lastName: "Prameswari",
      primaryInstrumentId: "inst-piano",
      secondaryInstrumentIds: [],
      skillLevel: "Beginner",
      learningGoal: "Performance",
      preferredLessonMode: "Studio",
      guardianIds: ["guardian-rina"],
      portalEnabled: true,
      musicNotes: "Perlu latihan tempo stabil.",
    },
  ],
  instructors: [
    {
      id: "instructor-budi",
      createdAt: now,
      updatedAt: now,
      instructorName: "Budi Santoso",
      instrumentIds: ["inst-piano", "inst-guitar"],
      levelFrom: "Beginner",
      levelTo: "Advanced",
      portalEnabled: true,
    },
  ],
  courses: [
    {
      id: "course-piano-beginner",
      createdAt: now,
      updatedAt: now,
      courseName: "Piano Beginner Private",
      instrumentId: "inst-piano",
      courseLevel: "Beginner",
      lessonType: "Private",
      durationMinutes: 60,
      defaultFee: 850000,
    },
  ],
  rooms: [
    {
      id: "room-piano-1",
      createdAt: now,
      updatedAt: now,
      roomName: "Piano Room 1",
      capacity: 2,
      instrumentIds: ["inst-piano"],
      isActive: true,
    },
  ],
  schedules: [
    {
      id: "schedule-studio-1",
      createdAt: now,
      updatedAt: now,
      courseId: "course-piano-beginner",
      studentId: "student-ayu",
      instructorId: "instructor-budi",
      instrumentId: "inst-piano",
      scheduleDate: "2026-05-17",
      fromTime: "10:00",
      toTime: "11:00",
      lessonMode: "Studio",
      studioRoomId: "room-piano-1",
      homeVisitAddress: "",
      travelNotes: "",
      privateLesson: true,
      recurringPattern: "Weekly",
      recurrenceEndDate: "2026-06-14",
      scheduleStatus: "Scheduled",
      originalScheduleId: "",
      rescheduleReason: "",
    },
  ],
  "student-attendance": [
    {
      id: "attendance-ayu-1",
      createdAt: now,
      updatedAt: now,
      studentId: "student-ayu",
      courseScheduleId: "schedule-studio-1",
      instrumentId: "inst-piano",
      date: "2026-05-17",
      status: "Present",
      absenceReason: "",
      makeupRequired: false,
      makeupScheduleId: "",
      parentNotified: false,
      absenceAlertKey: "",
    },
  ],
  "instructor-attendance": [
    {
      id: "instructor-attendance-budi-1",
      createdAt: now,
      updatedAt: now,
      instructorId: "instructor-budi",
      courseScheduleId: "schedule-studio-1",
      attendanceDate: "2026-05-17",
      instrumentId: "inst-piano",
      status: "Present",
      substituteInstructorId: "",
      notes: "Kelas berjalan sesuai jadwal.",
    },
  ],
  repertoires: [
    {
      id: "rep-minuet-g",
      createdAt: now,
      updatedAt: now,
      title: "Minuet in G",
      composerArtist: "J. S. Bach",
      instrumentId: "inst-piano",
      level: "Beginner",
      genre: "Classical",
      notes: "Materi awal koordinasi tangan kanan dan kiri.",
      isActive: true,
    },
  ],
  journals: [
    {
      id: "journal-ayu-1",
      createdAt: now,
      updatedAt: now,
      studentId: "student-ayu",
      instructorId: "instructor-budi",
      courseScheduleId: "schedule-studio-1",
      lessonDate: "2026-05-17",
      instrumentId: "inst-piano",
      level: "Beginner",
      attendanceId: "attendance-ayu-1",
      materialCovered: "Postur duduk, finger number, dan latihan tangan kanan.",
      techniqueFocus: "Koordinasi jari 1-2-3 tangan kanan.",
      repertoireIds: ["rep-minuet-g"],
      homework: "Latihan finger number 10 menit per hari.",
      teacherNotes: "Ayu cepat menangkap instruksi, perlu latihan tempo stabil.",
      progressRating: "Improving",
      parentVisible: true,
      submittedAt: "2026-05-17T11:05:00.000Z",
    },
  ],
  invoices: [
    {
      id: "invoice-ayu-2026-05",
      createdAt: now,
      updatedAt: now,
      studentId: "student-ayu",
      instrumentId: "inst-piano",
      billingPeriod: "2026-05",
      lessonPackage: "4x per bulan",
      amount: 850000,
      dueDate: "2026-05-20",
      status: "Unpaid",
    },
  ],
  notifications: [],
};
